language: java
sudo: false
jdk:
- oraclejdk7
- openjdk7
script: "./build.sh"
after_success:
- "./gradlew jacocoTestReport coveralls -S"
cache:
  directories:
  - "$HOME/.gradle/caches/"
before_install:
- openssl aes-256-cbc -K $encrypted_5d4ff8acf7ad_key -iv $encrypted_5d4ff8acf7ad_iv -in gradle.properties.enc -out gradle.properties -d